// @ts-nocheck
"use client";

import { useEffect, useMemo, useState } from "react";
import { usePathname, useRouter } from "next/navigation";

type Material={name:string;category:string;price:string;trend:string;demand:string;supplier:string;status:string};
type Supplier={name:string;speciality:string;coverage:string;lead:string;rating:string;status:string};
const materials:Material[]=[
{name:"Lamina Oak 08",category:"Laminates",price:"₹1,249",trend:"+8.4%",demand:"High",supplier:"Merino",status:"Watch"},
{name:"Urban Stone Grey",category:"Tiles",price:"₹118/sqft",trend:"+3.2%",demand:"High",supplier:"Kajaria",status:"Stable"},
{name:"Linea Walnut",category:"Wall Panels",price:"₹189/sqft",trend:"-1.8%",demand:"Rising",supplier:"Evolve",status:"Opportunity"},
{name:"Carrara Soft",category:"Quartz",price:"₹395/sqft",trend:"+5.7%",demand:"Medium",supplier:"Classic",status:"Stable"},
{name:"Terrazzo Sand",category:"Tiles",price:"₹96/sqft",trend:"+2.1%",demand:"Rising",supplier:"Orientbell",status:"Watch"},
{name:"Sierra Ash",category:"Laminates",price:"₹1,095",trend:"+6.3%",demand:"High",supplier:"Greenlam",status:"Stable"}];
const suppliers:Supplier[]=[
{name:"Merino Industries",speciality:"Laminates · Panels",coverage:"North + South",lead:"8–12 days",rating:"4.6",status:"Preferred"},
{name:"Kajaria Ceramics",speciality:"Tiles",coverage:"Pan India",lead:"5–8 days",rating:"4.5",status:"Preferred"},
{name:"Greenlam Industries",speciality:"Laminates · Surfaces",coverage:"Pan India",lead:"7–10 days",rating:"4.4",status:"Watch"},
{name:"Orientbell Tiles",speciality:"Tiles · Flooring",coverage:"South + West",lead:"4–7 days",rating:"4.3",status:"Stable"},
{name:"Evolve India",speciality:"Wall Panels",coverage:"South",lead:"6–9 days",rating:"4.2",status:"Stable"}];

const nav=[["dashboard","Dashboard","⌂"],["market","Market Intelligence","◌"],["materials","Material Intelligence","▧"],["suppliers","Supplier Intelligence","◈"],["pricing","Pricing & Trends","↗"],["reports","Reports & Insights","▤"],["saved","Saved Insights","♡"]];
const titleMap:Record<string,[string,string]>={dashboard:["Decision overview","A compact view of the commercial signals that need attention."],market:["Market intelligence","Track category movement, demand signals and competitive context."],materials:["Material intelligence","Search, compare and investigate materials across the catalogue."],suppliers:["Supplier intelligence","Understand supplier coverage, lead times and commercial signals."],pricing:["Pricing & trends","Find price gaps where competitiveness and margin quality diverge."],reports:["Reports & insights","Turn recurring analysis into shareable decision briefs."],saved:["Saved insights","Your working set of findings, hypotheses and follow-ups."],why:["Why Material Depot?","The product story behind a decision-ready intelligence layer."],settings:["Workspace settings","Control theme, profile preferences and demo workspace behaviour."]};

function Logo(){return <div className="hubLogo"><span>MD</span><i/></div>}
function Spark({kind="up"}){return <svg className="spark" viewBox="0 0 90 30"><path d={kind==="down"?"M2 6 C18 9 25 23 39 18 S62 11 88 24":"M2 25 C16 22 22 18 34 20 S53 8 64 12 S77 6 88 2"} fill="none" stroke="currentColor" strokeWidth="2"/></svg>}
function Icon({s}:{s:string}){return <span className="navIcon">{s}</span>}
function PanelTitle({title,action,onClick}:{title:string;action?:string;onClick?:()=>void}){return <div className="panelTitle"><div><span>{title}</span></div>{action&&<button onClick={onClick}>{action} →</button>}</div>}
function Insight({label,title,tone,onSave}:{label:string;title:string;tone:string;onSave:()=>void}){return <div className="insight"><span className={"tone "+tone}>{label}</span><p>{title}</p><button onClick={onSave} aria-label={"Save "+title}>♡</button></div>}

export default function HubView(){
 const pathname=usePathname(); const router=useRouter();
 const current=pathname.split("/").filter(Boolean)[1]||"dashboard";
 const [theme,setTheme]=useState<"light"|"dark">("light");
 const [search,setSearch]=useState(""); const [period,setPeriod]=useState("6M");
 const [category,setCategory]=useState("All"); const [demand,setDemand]=useState("All");
 const [saved,setSaved]=useState<string[]>([]); const [selected,setSelected]=useState<Material|null>(null);
 const [compare,setCompare]=useState<Material[]>([]); const [toast,setToast]=useState("");
 useEffect(()=>{const t=localStorage.getItem("md-theme") as "light"|"dark"|null;if(t)setTheme(t);const s=JSON.parse(localStorage.getItem("md-saved")||"[]");setSaved(s)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("md-theme",theme)},[theme]);
 useEffect(()=>{localStorage.setItem("md-saved",JSON.stringify(saved))},[saved]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2200);return()=>clearTimeout(t)},[toast]);
 const info=titleMap[current]||titleMap.dashboard;
 const filtered=useMemo(()=>materials.filter(m=>(category==="All"||m.category===category)&&(demand==="All"||m.demand===demand)&&[m.name,m.category,m.supplier].join(" ").toLowerCase().includes(search.toLowerCase())),[search,category,demand]);
 const save=(x:string)=>{setSaved(v=>v.includes(x)?v.filter(a=>a!==x):[...v,x]);setToast(saved.includes(x)?"Removed from saved insights":"Saved to decision queue")};
 const addCompare=(m:Material)=>{setCompare(v=>v.some(x=>x.name===m.name)?v.filter(x=>x.name!==m.name):v.length<3?[...v,m]:v);setToast(compare.some(x=>x.name===m.name)?"Removed from comparison":"Added to comparison")};
 return <div className="hubApp">
  <aside className="hubSide"><div className="sideBrand"><Logo/><div><b>Material Depot</b><small>INTELLIGENCE HUB</small></div></div>
   <div className="sideGroup"><small>WORKSPACE</small>{nav.map(([id,label,ic])=><button key={id} className={current===id?"sideNav active":"sideNav"} onClick={()=>router.push("/hub/"+id)}><Icon s={ic}/><span>{label}</span>{id==="saved"&&saved.length>0?<em>{saved.length}</em>:null}</button>)}</div>
   <div className="sideGroup lower"><small>COMPANY</small><button className={current==="why"?"sideNav active":"sideNav"} onClick={()=>router.push("/hub/why")}><Icon s="✦"/><span>Why Material Depot?</span></button><button className={current==="settings"?"sideNav active":"sideNav"} onClick={()=>router.push("/hub/settings")}><Icon s="⚙"/><span>Settings</span></button></div>
   <div className="userCard"><div className="userAvatar">PA</div><div><b>Pranavi Addanki</b><small>Business Analyst · Demo</small></div><button onClick={()=>router.push("/hub/settings")}>⋯</button></div>
  </aside>
  <main className="hubMain"><header className="hubTop"><div className="breadcrumb"><span>Intelligence Hub</span><b>/</b><strong>{info[0]}</strong></div><div className="topTools"><label className="hubSearch">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search materials, suppliers..." /></label><button className="topIcon" onClick={()=>setToast("No new decision alerts")}>◔</button><button className="themeToggle" onClick={()=>setTheme(theme==="light"?"dark":"light")}>{theme==="light"?"☾":"☀"}<span>{theme==="light"?"Dark":"Light"}</span></button><button className="topAvatar" onClick={()=>router.push("/hub/settings")}>PA</button></div></header>
   <div className="pageWrap"><div className="pageIntro"><div><span className="eyebrow">INTELLIGENCE WORKSPACE</span><h1>{info[0]}</h1><p>{info[1]}</p></div><div className="introRight"><span className="dataBadge"><i/> DEMO DATA · SIMULATED</span>{["dashboard","market","pricing"].includes(current)&&<div className="periods">{["30D","6M","12M"].map(p=><button key={p} className={period===(p==="30D"?"30D":p==="6M"?"6M":"12M")?"chosen":""} onClick={()=>setPeriod(p==="30D"?"30D":p==="6M"?"6M":"12M")}>{p}</button>)}</div>}</div></div>
    {current==="dashboard"&&<Dashboard router={router} onSave={save} period={period}/>}
    {current==="market"&&<Market period={period} setPeriod={setPeriod}/>}
    {current==="materials"&&<Materials items={filtered} category={category} setCategory={setCategory} demand={demand} setDemand={setDemand} onOpen={setSelected} onSave={save} onCompare={addCompare} saved={saved} compare={compare}/>}
    {current==="suppliers"&&<Suppliers items={suppliers} onSave={save}/>}
    {current==="pricing"&&<Pricing onSave={save} saved={saved} period={period}/>}
    {current==="reports"&&<Reports onOpen={()=>setToast("Report preview opened")}/>}
    {current==="saved"&&<Saved saved={saved} onRemove={save}/>}
    {current==="why"&&<Why/>}{current==="settings"&&<Settings theme={theme} setTheme={setTheme}/>}
   </div>
  </main>
  {selected&&<MaterialDetail material={selected} onClose={()=>setSelected(null)} onSave={save} onCompare={addCompare} comparing={compare.some(x=>x.name===selected.name)}/>}
  {compare.length>0&&<CompareBar items={compare} onClear={()=>setCompare([])} onOpen={()=>setSelected(compare[0])}/>}
  {toast&&<div className="toast">✓ {toast}</div>}
 </div>
}

function Dashboard({router,onSave,period}:{router:any;onSave:(x:string)=>void;period:string}){
 const mult=period==="30D"?.42:period==="12M"?1.85:1;
 const k=[["Revenue",`₹${(182.4*mult).toFixed(1)}L`,period==="30D"?"+2.7%":"+11.8%"],["Gross margin","31.6%",period==="12M"?"+3.2 pp":"+1.4 pp"],["AOV","₹46,280",period==="30D"?"+1.9%":"+6.2%"],["Conversion","8.7%",period==="12M"?"+1.8 pp":"+0.8 pp"]];
 return <div className="dash"><div className="kpiRow">{k.map((x,i)=><div className="dashKpi" key={x[0]}><small>{x[0]} · {period}</small><strong>{x[1]}</strong><span>↑ {x[2]} <em>vs prior period</em></span><Spark kind={i===3?"down":"up"}/></div>)}</div>
 <div className="dashGrid"><div className="panel marketPanel"><PanelTitle title="Market movement" action="Open market" onClick={()=>router.push("/hub/market")}/><div className="bigChart"><div className="chartLegend"><span>Composite category index · {period}</span><b>{period==="30D"?"104.2":period==="12M"?"118.9":"112.8"}</b></div><svg viewBox="0 0 700 230" preserveAspectRatio="none"><path d="M0 184 C60 178 78 155 132 165 S194 196 246 139 S325 112 369 127 S430 165 482 83 S565 80 700 28" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M0 184 C60 178 78 155 132 165 S194 196 246 139 S325 112 369 127 S430 165 482 83 S565 80 700 28 L700 230 L0 230Z" fill="currentColor" opacity=".08"/></svg><div className="chartAxis"><span>Start</span><span>Mid</span><span>Recent</span><span>Now</span></div></div></div>
 <div className="panel alertsPanel"><PanelTitle title="Decision queue" action="View all" onClick={()=>router.push("/hub/saved")}/><Insight label="PRICING" title="12 SKUs above modeled competitor median" tone="amber" onSave={()=>onSave("Pricing review · 12 SKUs")}/><Insight label="STORE" title="Jayanagar quote conversion trails the network" tone="red" onSave={()=>onSave("Store funnel · Jayanagar")}/><Insight label="CATEGORY" title="Wall Panels combine growth with margin quality" tone="green" onSave={()=>onSave("Category opportunity · Wall Panels")}/></div></div>
 <div className="sectionLabel">Explore intelligence</div><div className="moduleGrid">{[["market","Market Intelligence","Trends, movement and competitive context","↗"],["materials","Material Intelligence","Profiles, prices and demand signals","▧"],["suppliers","Supplier Intelligence","Coverage, lead times and supplier context","◈"],["pricing","Pricing & Trends","Price position and test opportunities","⌁"]].map(x=><button className="moduleCard" key={x[0]} onClick={()=>router.push("/hub/"+x[0])}><span>{x[3]}</span><b>{x[1]}</b><small>{x[2]}</small><i>Open workspace →</i></button>)}</div></div>
}

function Market({period,setPeriod}:{period:string;setPeriod:(x:string)=>void}){const rows=[["Laminates","+8.4%","31.2%","High"],["Tiles","+3.2%","27.8%","High"],["Quartz","+5.7%","18.6%","Medium"],["Wall Panels","+6.9%","12.4%","Rising"],["Flooring","+2.1%","10.0%","Stable"]];return <div className="contentGrid"><div className="panel wide"><PanelTitle title="Category movement" action={period} onClick={()=>setPeriod(period==="12M"?"6M":period==="6M"?"30D":"12M")}/><div className="bigChart tall"><div className="chartLegend"><span>Composite market index · {period}</span><b>{period==="30D"?"104.2":period==="12M"?"118.9":"112.8"}</b></div><svg viewBox="0 0 900 280" preserveAspectRatio="none"><path d="M0 220 C70 200 120 214 170 175 S260 205 330 142 S410 180 480 120 S560 145 630 88 S740 120 900 42" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M0 220 C70 200 120 214 170 175 S260 205 330 142 S410 180 480 120 S560 145 630 88 S740 120 900 42 L900 280 L0 280Z" fill="currentColor" opacity=".08"/></svg></div><table className="proTable"><thead><tr><th>Category</th><th>Price movement</th><th>Revenue mix</th><th>Demand</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td>{r[2]}</td><td><span className="statusChip">{r[3]}</span></td></tr>)}</tbody></table></div><div className="panel"><PanelTitle title="Signals" action="Decision logic" onClick={()=>{}}/><div className="signalList">{["Premium laminate demand accelerating","Quartz price spread narrowing","South India tile availability improving","Wall panel search interest rising"].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span><em>{i%2?"+4.1%":"+8.4%"}</em></div>)}</div><div className="evidenceBox"><b>How to read this</b><p>Signals combine modeled price movement, demand and revenue mix. They are hypotheses for investigation, not internal Material Depot facts.</p></div></div></div>}

function Materials({items,onOpen,onSave,onCompare,saved,compare,category,setCategory,demand,setDemand}:{items:Material[];onOpen:(m:Material)=>void;onSave:(x:string)=>void;onCompare:(m:Material)=>void;saved:string[];compare:Material[];category:string;setCategory:(x:string)=>void;demand:string;setDemand:(x:string)=>void}){const cats=["All",...Array.from(new Set(materials.map(m=>m.category)))];return <div><div className="filterBar"><span>{items.length} of {materials.length} materials</span><select value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(x=><option key={x}>{x}</option>)}</select><select value={demand} onChange={e=>setDemand(e.target.value)}>{["All","High","Medium","Rising"].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>{setCategory("All");setDemand("All")}}>Reset</button></div>{items.length?<div className="materialGrid">{items.map(m=><article className="materialCard" key={m.name}><div className="materialTop"><span>{m.category}</span><button onClick={()=>onSave("Material · "+m.name)}>{saved.includes("Material · "+m.name)?"♥":"♡"}</button></div><h3>{m.name}</h3><div className="materialPrice"><b>{m.price}</b><span>{m.trend}</span></div><Spark/><div className="materialMeta"><span>Demand <b>{m.demand}</b></span><span>Supplier <b>{m.supplier}</b></span></div><div className="materialActions"><button className="textAction" onClick={()=>onOpen(m)}>View profile →</button><button className={compare.some(x=>x.name===m.name)?"compare chosen":"compare"} onClick={()=>onCompare(m)}>{compare.some(x=>x.name===m.name)?"Compared ✓":"Compare"}</button></div></article>)}</div>:<div className="emptyState panel"><b>No materials match these filters.</b><span>Reset the filters or broaden the search.</span></div>}</div>}

function Suppliers({items,onSave}:{items:Supplier[];onSave:(x:string)=>void}){return <div className="panel"><div className="tableHead"><span>Supplier directory · {items.length} active profiles</span><button onClick={()=>onSave("Supplier directory · current view")}>Save view ♡</button></div><table className="proTable"><thead><tr><th>Supplier</th><th>Speciality</th><th>Coverage</th><th>Lead time</th><th>Signal</th></tr></thead><tbody>{items.map(s=><tr key={s.name}><td><b>{s.name}</b><small>Score {s.rating}/5</small></td><td>{s.speciality}</td><td>{s.coverage}</td><td>{s.lead}</td><td><span className="statusChip">{s.status}</span></td></tr>)}</tbody></table></div>}

function Pricing({onSave,saved,period}:{onSave:(x:string)=>void;saved:string[];period:string}){const rows=[["Lamina Oak 08","Laminates","₹1,249","₹1,149","1.09x","Review"],["Urban Stone Grey","Tiles","₹118","₹112","1.05x","Review"],["Linea Walnut","Wall Panels","₹189","₹205","0.92x","Protect"],["Carrara Soft","Quartz","₹395","₹410","0.96x","Protect"],["Terrazzo Sand","Tiles","₹96","₹101","0.95x","Test"]];const risky=rows.filter(r=>r[4]==="1.09x"||r[4]==="1.05x").length;return <div className="contentGrid"><div className="panel wide"><div className="tableHead"><span>Pricing opportunity set · {period}</span><button onClick={()=>onSave("Pricing review · current set")}>{saved.includes("Pricing review · current set")?"Saved ✓":"Save view ♡"}</button></div><div className="decisionStrip"><b>{risky}</b><span>high-price-position items</span><b>31.6%</b><span>modeled portfolio margin</span><b>5</b><span>testable SKUs</span></div><table className="proTable"><thead><tr><th>Material</th><th>Category</th><th>MD price</th><th>Comp. median</th><th>PCI</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td><span className={"pci "+(r[4].startsWith("1.")?"risk":"safe")}>{r[4]}</span></td><td><button className="inlineAction" onClick={()=>onSave("Pricing action · "+r[0])}>{r[5]} + save</button></td></tr>)}</tbody></table></div><div className="panel pricingExplain"><span className="eyebrow">DECISION FRAMEWORK</span><h2>Price position × margin quality</h2><p>PCI above 1.00 means the modeled Material Depot price is above the comparable median. Use it as a test signal, not a final pricing decision.</p><div className="miniMatrix"><span>PROTECT</span><span>REVIEW</span><span>TEST</span><span>FIX</span></div><button className="primaryAction" onClick={()=>onSave("Pricing test cohort · 5 SKUs")}>Save test cohort</button></div></div>}

function Reports({onOpen}:{onOpen:()=>void}){return <div className="reportGrid">{[["Monthly pricing review","Pricing · 24 Jun 2026","3 actions · 12 SKUs","Pricing"],["Experience centre pulse","Stores · 18 Jun 2026","5 centres · funnel","Store"],["Category growth brief","Categories · 12 Jun 2026","6 categories · margin","Category"]].map((r,i)=><article className="reportCard" key={r[0]}><div className="reportCover"><span>MD / {r[3].toUpperCase()}</span><b>Decision<br/>Brief</b><i>{String(i+1).padStart(2,"0")}</i></div><span className="eyebrow">{r[1]}</span><h3>{r[0]}</h3><p>{r[2]}</p><button onClick={onOpen}>Open report →</button></article>)}</div>}

function Saved({saved,onRemove}:{saved:string[];onRemove:(x:string)=>void}){return <div className="panel savedPanel"><div className="tableHead"><span>{saved.length} saved insights</span><span className="muted">Persisted decision queue</span></div>{saved.length?saved.map((x,i)=><div className="savedRow" key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span><button onClick={()=>onRemove(x)}>Remove</button></div>):<div className="emptyState"><b>Your decision queue is empty.</b><span>Save an insight from any intelligence workspace to keep it here.</span></div>}</div>}

function MaterialDetail({material,onClose,onSave,onCompare,comparing}:{material:Material;onClose:()=>void;onSave:(x:string)=>void;onCompare:(m:Material)=>void;comparing:boolean}){return <div className="modalShade" onClick={onClose}><div className="detailModal" onClick={e=>e.stopPropagation()}><button className="closeBtn" onClick={onClose}>×</button><span className="eyebrow">MATERIAL PROFILE</span><h2>{material.name}</h2><div className="detailTags"><span>{material.category}</span><span>{material.status}</span></div><div className="profileMetrics"><div><small>Current price</small><b>{material.price}</b></div><div><small>Price trend</small><b>{material.trend}</b></div><div><small>Demand</small><b>{material.demand}</b></div></div><div className="detailChart"><Spark/><div className="chartAxis"><span>90D</span><span>60D</span><span>30D</span><span>NOW</span></div></div><div className="detailRows"><p><span>Primary supplier</span><b>{material.supplier}</b></p><p><span>Market status</span><b>{material.status}</b></p><p><span>Comparable set</span><b>14 modeled SKUs</b></p></div><div className="modalActions"><button className="primaryAction" onClick={()=>onSave("Material · "+material.name)}>Save insight</button><button className={comparing?"compare chosen":"compare"} onClick={()=>onCompare(material)}>{comparing?"Compared ✓":"Add to compare"}</button></div></div></div>}

function CompareBar({items,onClear,onOpen}:{items:Material[];onClear:()=>void;onOpen:()=>void}){return <div className="compareBar"><div><b>{items.length}/3 comparison set</b>{items.map(x=><span key={x.name}>{x.name}</span>)}</div><button onClick={onOpen}>Open comparison</button><button onClick={onClear}>Clear</button></div>}

function Why(){return <div className="whyGrid">{[["01","Faster intelligence","Reduce the time between a market signal and a commercial decision.","⌁"],["02","Centralised context","Bring materials, suppliers, pricing and trends into one working view.","▧"],["03","Ground-level decisions","Connect dashboard signals with store and client context before acting.","◌"],["04","Actionable reporting","Turn recurring analysis into concise briefs that leadership can use.","▤"]].map(x=><article key={x[0]}><span>{x[3]}</span><small>{x[0]}</small><h2>{x[1]}</h2><p>{x[2]}</p><i>Explore capability →</i></article>)}</div>}

function Settings({theme,setTheme}:{theme:"light"|"dark";setTheme:(x:"light"|"dark")=>void}){return <div className="settingsGrid"><div className="panel settingsPanel"><span className="eyebrow">APPEARANCE</span><h2>Workspace theme</h2><p>Choose a display mode. Your preference is stored locally for this browser.</p><div className="themeCards"><button className={theme==="light"?"chosen":""} onClick={()=>setTheme("light")}><div className="lightPreview"/>Light<small>Warm paper · high clarity</small></button><button className={theme==="dark"?"chosen":""} onClick={()=>setTheme("dark")}><div className="darkPreview"/>Dark<small>Deep green · focused work</small></button></div></div><div className="panel settingsPanel"><span className="eyebrow">PROFILE</span><h2>Pranavi Addanki</h2><p>Business Analyst · Portfolio workspace</p><div className="settingLine"><span>Workspace</span><b>Material Depot Intelligence Hub</b></div><div className="settingLine"><span>Data mode</span><b>Simulated / demo</b></div><div className="settingLine"><span>Last updated</span><b>24 Jun 2026 · 09:40 IST</b></div></div></div>}
